num1 = input('first number: ')
num2 = input('second number: ')
sum = float(num1) + float(num2)
print('sum of {0} and {1} is {2}'.format(num1, num2, sum))
min = float(num1) - float(num2)
print('subtraction of {0} and {1} is {2}'.format(num1, num2, min))
Mul = float(num1) * float(num2)
print('multiplication of {0} and {1} is {2}'.format(num1, num2, Mul))
div = float(num1) / float(num2)
print('division of {0} and {1} is {2}'.format(num1, num2, div))